application: test
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /images
  static_dir: images

- url: /fonts
  static_dir: static/fonts

- url: /.*
  script: main.app

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /bootstrap
  static_dir: static/bootstrap

libraries:
- name: jinja2
  version: latest